[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "nixbot_frontend"
author = "Robert T. McGibbon"

[tool.flit.scripts]
nixbot-frontend = "nixbot_frontend.frontend:main"
